let a=10;
let b=5;
let c=7;
let soma=a+b+c;
let multiplicação=a*b*c;
let divisão=a/b/c;
let subtração=a-b-c;
console.log(" o resultado da multiplicação é: " + multiplicação);
console.log(" o resultado da soma é: " + soma);
console.log(" o resultado da divisão é: " + divisão);
console.log(" o resultado da subtração é: " + subtração);